const FILE = 'file';
const FOLDER = 'folder';
const ROOT = 'root/';
const ADD_ENTRY = 'ADD_ENTRY';
const DELETE_ENTRY = 'DELETE_ENTRY';
const MULTIPLE_DELETE = 'MULTIPLE_DELETE';
const CHANGE_PATH = 'CHANGE_PATH';
const RENAME_ENTRY = 'RENAME_ENTRY';

export {FILE, FOLDER, ROOT, ADD_ENTRY, DELETE_ENTRY, MULTIPLE_DELETE, CHANGE_PATH, RENAME_ENTRY}